# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://discount-manager-demo.vercel.app"
embedded = true
name = "discount-manager"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://discount-manager-demo.vercel.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
